### ISSUE TITLE
can't use shader on vesa modes

### ISSUE THREAD

**Issue by Glog78** [duganchen/dosbox#8] opened 2017-02-27 21:23 UTC
Hi i try to get 11th hour running but it only runs with overlay.

DOSBox version SVN
Copyright 2002-2015 DOSBox Team, published under GNU GPL.
---
CONFIG:Loading primary settings from config file /home/******/dosbox_11th_test.conf
SDL: Current window pixel format: SDL_PIXELFORMAT_RGB888
MIXER: Got different values from SDL: freq 44100, blocksize 512
MT32: Control ROM file not found
ALSA:Client initialised [128:0]
MIDI: Opened device:alsa
Game resolution: 640x400
DOSBox has switched to max cycles, because of the setting: cycles=auto.
If the game runs too fast, try a fixed cycles amount in DOSBox's options.
Exit to error: Could not retrieve window surface: No hardware accelerated renderers available

http://sprunge.us/BJSN

**Comment by duganchen** [comment] 2017-02-27 21:55
Please post the full output of the following command:

    glxinfo

**Comment by Glog78** [comment] 2017-02-27 21:57
http://sprunge.us/LjbE

**Comment by duganchen** [comment] 2017-02-27 22:12
Is the first attachment (which has the output set to OpenGL) the one that causes this issue for you?

Does the crash happen immediately, or do you have to play the game a bit first before it crashes?

Does it happen with other games?

**Comment by duganchen** [comment] 2017-02-27 22:12
Also, why does your subject line have the word "Vesa"?

**Comment by duganchen** [comment] 2017-02-27 22:16
I have the same video card as you (375.26 drivers though). I have the Steam release of 11th Hour. I'll do a test with your .conf tonight and I'll let you know what happens.

**Comment by Glog78** [comment] 2017-02-27 22:20
yeah the first attachment ist the one that crashes (overlay works)
it crashes immediately
vesa = because the game uses -> https://en.wikipedia.org/wiki/VESA_BIOS_Extensions#VESA_BIOS_Extensions_.28VBE_core.29_2.0_.5BNovember_1994.5D 
and yes its one of the few which uses vbe 2.0 (btw the vbe2.0 implementation on dosbox isn't realy great too)

Another one is TEX Murphy "Under the killing moon" (i'm nearly sure it doesn't use vbe) and i think "Realms of Arkania 3" suffers from it too.

**Comment by duganchen** [comment] 2017-02-28 03:27
I'd like to at least determine whether this was a bug I introduced (possibly with my work on the OpenGL 3 backend) or if it was also  in the original SDL 2 patch. Unfortunately, I didn't get anywhere with that yet.

It turns out that I can't test with 11th Hour because the Steam version (which I have) doesn't include the DOS build.

I don't have Realms of Arkania 3.

Now, I did manage to test with GOG's release of Under A Killing Moon, and it definitely works with that. The .conf file I used was just the official one, with the output set to OpenGL and a can't-miss-it shader added:

    [sdl]
    output=opengl
    gl.shader=FixingPixelArt

    [IPX]
    Enable=0
    Connection=0
    ipx=false

    [autoexec]
    # Lines in this section will be run at startup.

    @ECHO OFF
    mount C "data"
    c:
    imgmount D "UAKM.GOG" -t iso
    cls
    tex197.exe
    exit

Honestly, I'm not really sure what my next steps need to be.

**Comment by duganchen** [comment] 2017-02-28 15:07
As you've specifically said that this is reproducible with Under a Killing Moon, and I cannot reproduce it with Under A Killing Moon, I have no choice but to close this. Sorry.

**Closed as completed by duganchen** 2017-02-28 15:07 UTC

**Comment by duganchen** [comment] 2017-02-28 15:38
BTW, Gabriel Knight 1 in high-res mode uses an SVGA VESA mode. I know off the top of my head that that  definitely works.

**Comment by duganchen** [comment] 2017-02-28 15:55
I can't really think of what you might be doing differently. 

As for wild speculation... 

I am of course using SDL 2.0.5, and I assume you are too.

You're also using the Beta NVidia drivers. I really, really hope that that's not the factor, but that's the only other difference I can think of.

**Comment by Glog78** [comment] 2017-02-28 17:57
Ok now i'm back home , a little earlier than usuall. So one step after another.

What can be different than your setup:
 - Distribution: archlinux
 - i use kernel mode settings -> https://wiki.archlinux.org/index.php/NVIDIA#DRM_kernel_mode_setting
 - i use a specific xorg.conf for my setup so my monitor doesn't need to reset the resolution even on weird old modes -> http://sprunge.us/MYOh

PS i'm sorry under the killing moon does indeed run. I dunno what i did wrong the first time.

**Comment by duganchen** [comment] 2018-01-30 04:46
> i use a specific xorg.conf for my setup so my monitor doesn't need to reset the resolution even on weird old modes -> http://sprunge.us/MYOh

I'm just going to say, for the benefit of anyone else who might find this issue, that this is obviously not a configuration that you can expect me, or anyone else, to support.

**Comment by Glog78** [comment] 2018-01-30 13:05
Duganchen , this config is the old way from the nvidia driver to do gpu scalling. So basically i tell the nvidia driver to accept all listed resultions and scall them up to 1920x1080.  Also for better vsync on nvidia there is compositing on. 

The rest is just to disable autodetection of any displaymodes and setup only one 1920x1080 mode for the display (ignore edid / ignore x-server detection / ignore vesa modes).
